#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use App\Analyseur;
use App\Refactoriseur;

$command = $argv[1] ?? '';

switch ($command) {
    case 'analyse':
        $analyseur = new Analyseur();
        // Call the analyser
        // $analyseur->run(); // Uncomment to execute the analysis
        break;
    case 'refactor':
        $refactoriseur = new Refactoriseur();
        // Call the refactorer
        // $refactoriseur->run(); // Uncomment to execute the refactoring
        break;
    default:
        echo 'Commande non reconnue.';
}